import { useEffect } from 'react'
import { useTranslation } from 'react-i18next'
import SEO from '../components/SEO'
import { useLang } from '../i18n/LangContext'

const CONTENT = {
  ca: { legal: ['Avís legal', 'Aquest espai ha d’identificar la raó social, el NIF/CIF, el domicili social i, si escau, les dades registrals de la persona titular del web.', 'Dades pendents de facilitar pel titular: raó social · NIF/CIF · domicili social · dades registrals.'], privacy: ['Política de privacitat', 'Bo·TiC tracta les dades que faciliten les persones usuàries en les consultes, les comunicacions i les reserves realitzades mitjançant el servei extern MyRestoo.', 'Per exercir els drets d’accés, rectificació, supressió, oposició, limitació o portabilitat, escriviu a: [CORREU RGPD PENDENT].'], cookies: ['Política de cookies', 'Aquest web només activa les cookies d’analítica (Google Analytics 4 i Microsoft Clarity) i de màrqueting (Meta Pixel) després del consentiment exprés de la persona usuària.', 'Podeu retirar o modificar el consentiment en qualsevol moment des de «Preferències de cookies». MyRestoo és un servei extern de reserves i no carrega cookies dins d’aquest web mentre només s’hi accedeixi amb enllaç extern.'] },
  es: { legal: ['Aviso legal', 'Este espacio debe identificar la razón social, el NIF/CIF, el domicilio social y, en su caso, los datos registrales de la persona titular de la web.', 'Datos pendientes de facilitar por la titular: razón social · NIF/CIF · domicilio social · datos registrales.'], privacy: ['Política de privacidad', 'Bo·TiC trata los datos facilitados en consultas, comunicaciones y reservas realizadas mediante el servicio externo MyRestoo.', 'Para ejercer los derechos de acceso, rectificación, supresión, oposición, limitación o portabilidad, escriba a: [CORREO RGPD PENDIENTE].'], cookies: ['Política de cookies', 'Esta web solo activa cookies de analítica (Google Analytics 4 y Microsoft Clarity) y marketing (Meta Pixel) tras el consentimiento expreso de la persona usuaria.', 'Puede retirar o modificar el consentimiento en cualquier momento desde «Preferencias de cookies». MyRestoo es un servicio externo de reservas y no carga cookies en esta web mientras se acceda mediante enlace externo.'] },
  en: { legal: ['Legal notice', 'This section must identify the legal name, tax ID, registered address and, where applicable, company registration details of the website owner.', 'Details to be provided by the owner: legal name · tax ID · registered address · company registration details.'], privacy: ['Privacy policy', 'Bo·TiC processes the data provided through enquiries, communications and reservations made through the external MyRestoo service.', 'To exercise access, rectification, erasure, objection, restriction or portability rights, write to: [PENDING GDPR EMAIL].'], cookies: ['Cookie policy', 'This website only enables analytics cookies (Google Analytics 4 and Microsoft Clarity) and marketing cookies (Meta Pixel) after the user’s explicit consent.', 'You can withdraw or change consent at any time from “Cookie preferences”. MyRestoo is an external reservation service and does not load cookies on this website while accessed through an external link.'] },
  fr: { legal: ['Mentions légales', 'Cet espace doit identifier la raison sociale, le NIF/CIF, le domicile social et, le cas échéant, les données d’immatriculation de la personne titulaire du site.', 'Informations à fournir par le titulaire : raison sociale · NIF/CIF · domicile social · données d’immatriculation.'], privacy: ['Politique de confidentialité', 'Bo·TiC traite les données fournies lors des demandes, communications et réservations réalisées via le service externe MyRestoo.', 'Pour exercer les droits d’accès, rectification, effacement, opposition, limitation ou portabilité, écrivez à : [E-MAIL RGPD À COMPLÉTER].'], cookies: ['Politique de cookies', 'Ce site active les cookies d’analyse (Google Analytics 4 et Microsoft Clarity) et de marketing (Meta Pixel) uniquement après le consentement explicite de la personne utilisatrice.', 'Vous pouvez retirer ou modifier votre consentement à tout moment depuis « Préférences de cookies ». MyRestoo est un service de réservation externe qui ne charge pas de cookies dans ce site lorsqu’il est utilisé par lien externe.'] },
}

export default function Legal({ type }) {
  const { t } = useTranslation(); const lang = useLang(); const contentType = type === 'preferences' ? 'cookies' : type; const [title, lead, details] = (CONTENT[lang] || CONTENT.ca)[contentType]
  useEffect(() => {
    if (type !== 'preferences') return undefined
    const timer = window.setTimeout(() => window.dispatchEvent(new Event('botic:cookie-preferences')), 0)
    return () => window.clearTimeout(timer)
  }, [type])
  return <><SEO title={title} description={lead} pageKey={contentType} /><main className="legal-page"><div className="container-max"><span>BO·TIC</span><h1>{type === 'preferences' ? t('footer.cookiePreferences') : title}</h1><p className="legal-lead">{lead}</p><div className="legal-rule" /><p>{details}</p>{contentType === 'cookies' && <button className="legal-preferences" onClick={() => window.dispatchEvent(new Event('botic:cookie-preferences'))}>{t('footer.cookiePreferences')}</button>}</div></main></>
}
