import { useEffect } from 'react'
import { useTranslation } from 'react-i18next'
import SEO from '../components/SEO'
import { useLang } from '../i18n/LangContext'

const CONTENT = {
  ca: { legal: ['Avís legal', 'Aquest espai ha d’identificar la raó social, el NIF/CIF, el domicili social i, si escau, les dades registrals de la persona titular del web.', 'Dades pendents de facilitar pel titular: raó social · NIF/CIF · domicili social · dades registrals.'], privacy: ['Política de privacitat', 'Bo·TiC tracta les dades que faciliten les persones usuàries en les consultes, les comunicacions i les reserves realitzades mitjançant el servei extern MyRestoo.', 'Per exercir els drets d’accés, rectificació, supressió, oposició, limitació o portabilitat, escriviu a: [CORREU RGPD PENDENT].'], cookies: ["Política de cookies", "Aquest web utilitza cookies necessàries i activa Google Analytics 4 només amb el vostre consentiment. No hi ha eines publicitàries activades.", "Podeu modificar la decisió des de «Preferències de cookies». La pàgina de reserves integra el formulari de Restoo, que es connecta amb aquest proveïdor per mostrar disponibilitat i gestionar la reserva. Les reserves funcionen sense acceptar l’analítica."] },
  es: { legal: ['Aviso legal', 'Este espacio debe identificar la razón social, el NIF/CIF, el domicilio social y, en su caso, los datos registrales de la persona titular de la web.', 'Datos pendientes de facilitar por la titular: razón social · NIF/CIF · domicilio social · datos registrales.'], privacy: ['Política de privacidad', 'Bo·TiC trata los datos facilitados en consultas, comunicaciones y reservas realizadas mediante el servicio externo MyRestoo.', 'Para ejercer los derechos de acceso, rectificación, supresión, oposición, limitación o portabilidad, escriba a: [CORREO RGPD PENDIENTE].'], cookies: ["Política de cookies", "Esta web utiliza cookies necesarias y activa Google Analytics 4 solo con su consentimiento. No hay herramientas publicitarias activadas.", "Puede modificar su decisión desde «Preferencias de cookies». La página de reservas integra el formulario de Restoo, que se conecta con este proveedor para mostrar disponibilidad y gestionar la reserva. Las reservas funcionan sin aceptar la analítica."] },
  en: { legal: ['Legal notice', 'This section must identify the legal name, tax ID, registered address and, where applicable, company registration details of the website owner.', 'Details to be provided by the owner: legal name · tax ID · registered address · company registration details.'], privacy: ['Privacy policy', 'Bo·TiC processes the data provided through enquiries, communications and reservations made through the external MyRestoo service.', 'To exercise access, rectification, erasure, objection, restriction or portability rights, write to: [PENDING GDPR EMAIL].'], cookies: ["Cookie policy", "This website uses necessary cookies and only enables Google Analytics 4 with your consent. No advertising tools are enabled.", "You can change your choice in Cookie preferences. The reservations page embeds the Restoo form and connects to this provider to display availability and manage bookings. Booking works without accepting analytics."] },
  fr: { legal: ['Mentions légales', 'Cet espace doit identifier la raison sociale, le NIF/CIF, le domicile social et, le cas échéant, les données d’immatriculation de la personne titulaire du site.', 'Informations à fournir par le titulaire : raison sociale · NIF/CIF · domicile social · données d’immatriculation.'], privacy: ['Politique de confidentialité', 'Bo·TiC traite les données fournies lors des demandes, communications et réservations réalisées via le service externe MyRestoo.', 'Pour exercer les droits d’accès, rectification, effacement, opposition, limitation ou portabilité, écrivez à : [E-MAIL RGPD À COMPLÉTER].'], cookies: ["Politique de cookies", "Ce site utilise des cookies nécessaires et active Google Analytics 4 uniquement avec votre consentement. Aucun outil publicitaire n’est activé.", "Vous pouvez modifier votre choix dans les préférences de cookies. La page de réservation intègre le formulaire Restoo et se connecte à ce prestataire pour afficher les disponibilités et gérer les réservations. La réservation fonctionne sans accepter les cookies d’analyse."] },
}

export default function Legal({ type }) {
  const { t } = useTranslation(); const lang = useLang(); const contentType = type === 'preferences' ? 'cookies' : type; const [title, lead, details] = (CONTENT[lang] || CONTENT.ca)[contentType]
  useEffect(() => {
    if (type !== 'preferences') return undefined
    const timer = window.setTimeout(() => window.dispatchEvent(new Event('botic:cookie-preferences')), 0)
    return () => window.clearTimeout(timer)
  }, [type])
  return <><SEO title={title} description={lead} pageKey={contentType} noindex={contentType !== 'cookies' || type === 'preferences'} /><main className="legal-page"><div className="container-max"><span>BO·TIC</span><h1>{type === 'preferences' ? t('footer.cookiePreferences') : title}</h1><p className="legal-lead">{lead}</p><div className="legal-rule" /><p>{details}</p>{contentType === 'cookies' && <button className="legal-preferences" onClick={() => window.dispatchEvent(new Event('botic:cookie-preferences'))}>{t('footer.cookiePreferences')}</button>}</div></main></>
}
