import { useEffect } from 'react'
import { useTranslation } from 'react-i18next'
import SEO from '../components/SEO'
import { useLang } from '../i18n/LangContext'

const CONTENT = {
  ca: { legal: ['Avís legal', 'La titular del web és Bo.TiC Alta Gastronomia S.L., amb NIF B17979378 i domicili fiscal a Av. Costa Brava, 6, 17121 Corçà, Girona, Espanya.', 'Podeu contactar amb la titular mitjançant les dades de contacte següents.'], privacy: ['Política de privacitat', 'Bo.TiC Alta Gastronomia S.L. és la responsable del tractament de les dades que faciliten les persones usuàries en les consultes, les comunicacions i les reserves realitzades mitjançant el servei extern MyRestoo.', 'Per exercir els drets d’accés, rectificació, supressió, oposició, limitació o portabilitat, escriviu a: restaurant@bo-tic.cat.'], cookies: ["Política de cookies", "Aquest web utilitza cookies necessàries i activa Google Analytics 4 només amb el vostre consentiment. No hi ha eines publicitàries activades.", "Podeu modificar la decisió des de «Preferències de cookies». La pàgina de reserves integra el formulari de Restoo, que es connecta amb aquest proveïdor per mostrar disponibilitat i gestionar la reserva. Les reserves funcionen sense acceptar l’analítica."] },
  es: { legal: ['Aviso legal', 'La titular de la web es Bo.TiC Alta Gastronomia S.L., con NIF B17979378 y domicilio fiscal en Av. Costa Brava, 6, 17121 Corçà, Girona, España.', 'Puede contactar con la titular mediante los siguientes datos de contacto.'], privacy: ['Política de privacidad', 'Bo.TiC Alta Gastronomia S.L. es la responsable del tratamiento de los datos facilitados en consultas, comunicaciones y reservas realizadas mediante el servicio externo MyRestoo.', 'Para ejercer los derechos de acceso, rectificación, supresión, oposición, limitación o portabilidad, escriba a: restaurant@bo-tic.cat.'], cookies: ["Política de cookies", "Esta web utiliza cookies necesarias y activa Google Analytics 4 solo con su consentimiento. No hay herramientas publicitarias activadas.", "Puede modificar su decisión desde «Preferencias de cookies». La página de reservas integra el formulario de Restoo, que se conecta con este proveedor para mostrar disponibilidad y gestionar la reserva. Las reservas funcionan sin aceptar la analítica."] },
  en: { legal: ['Legal notice', 'This website is owned by Bo.TiC Alta Gastronomia S.L., tax ID B17979378, with fiscal address at Av. Costa Brava, 6, 17121 Corçà, Girona, Spain.', 'You can contact the website owner using the contact details below.'], privacy: ['Privacy policy', 'Bo.TiC Alta Gastronomia S.L. is the controller of the data provided through enquiries, communications and reservations made through the external MyRestoo service.', 'To exercise access, rectification, erasure, objection, restriction or portability rights, write to: restaurant@bo-tic.cat.'], cookies: ["Cookie policy", "This website uses necessary cookies and only enables Google Analytics 4 with your consent. No advertising tools are enabled.", "You can change your choice in Cookie preferences. The reservations page embeds the Restoo form and connects to this provider to display availability and manage bookings. Booking works without accepting analytics."] },
  fr: { legal: ['Mentions légales', 'Ce site appartient à Bo.TiC Alta Gastronomia S.L., numéro fiscal B17979378, dont l’adresse fiscale est Av. Costa Brava, 6, 17121 Corçà, Girona, Espagne.', 'Vous pouvez contacter la société aux coordonnées ci-dessous.'], privacy: ['Politique de confidentialité', 'Bo.TiC Alta Gastronomia S.L. est responsable du traitement des données fournies lors des demandes, communications et réservations réalisées via le service externe MyRestoo.', 'Pour exercer les droits d’accès, rectification, effacement, opposition, limitation ou portabilité, écrivez à : restaurant@bo-tic.cat.'], cookies: ["Politique de cookies", "Ce site utilise des cookies nécessaires et active Google Analytics 4 uniquement avec votre consentement. Aucun outil publicitaire n’est activé.", "Vous pouvez modifier votre choix dans les préférences de cookies. La page de réservation intègre le formulaire Restoo et se connecte à ce prestataire pour afficher les disponibilités et gérer les réservations. La réservation fonctionne sans accepter les cookies d’analyse."] },
}

export default function Legal({ type }) {
  const { t } = useTranslation(); const lang = useLang(); const contentType = type === 'preferences' ? 'cookies' : type; const [title, lead, details] = (CONTENT[lang] || CONTENT.ca)[contentType]
  useEffect(() => {
    if (type !== 'preferences') return undefined
    const timer = window.setTimeout(() => window.dispatchEvent(new Event('botic:cookie-preferences')), 0)
    return () => window.clearTimeout(timer)
  }, [type])
  return <><SEO title={title} description={lead} pageKey={contentType} noindex={contentType !== 'cookies' || type === 'preferences'} /><main className="legal-page"><div className="container-max"><span>BO·TIC</span><h1>{type === 'preferences' ? t('footer.cookiePreferences') : title}</h1><p className="legal-lead">{lead}</p><div className="legal-rule" /><p>{details}</p><address style={{ fontStyle: 'normal', marginTop: '2rem', lineHeight: 1.8 }}><strong>Bo.TiC Alta Gastronomia S.L.</strong><br />NIF: B17979378<br />Av. Costa Brava, 6 · 17121 Corçà · Girona · ES<br /><a href="mailto:restaurant@bo-tic.cat">restaurant@bo-tic.cat</a><br /><a href="tel:+34972630869">+34 972 630 869</a></address>{contentType === 'cookies' && <button className="legal-preferences" onClick={() => window.dispatchEvent(new Event('botic:cookie-preferences'))}>{t('footer.cookiePreferences')}</button>}</div></main></>
}
